/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaspbo;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER.DX
 */
public class Utama extends javax.swing.JFrame {

    DefaultTableModel model;
    
    public Utama() {
        initComponents();
        cboKategori.setSelectedIndex(-1);
        
        String []judul = {"Kode","Merk","Kategori","Tipe","Warna"};
        model = new DefaultTableModel(judul,0);
        tbMobil.setModel(model);
        
        tampilData();
    
    tbMobil.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int selectedRow = tbMobil.getSelectedRow();
                if(selectedRow != -1) {
                    String kode = model.getValueAt(selectedRow, 0).toString();
                    String merk = model.getValueAt(selectedRow, 1).toString();
                    String kategori = model.getValueAt(selectedRow, 2).toString();
                    String tipe = model.getValueAt(selectedRow, 3).toString();
                    String warna = model.getValueAt(selectedRow, 4).toString();
                    
                    txtMerk.setText(merk);
                    txtKode.setText(kode);
                    txtWarna.setText(warna);
                    
                    cboKategori.setSelectedItem(kategori);
                    
                    if(tipe.equals("Facelift")) {
                        rbFacelift.setSelected(true);
                    }
                    else {
                        rbHatchback.setSelected(true);
                    }

                    txtKode.setEditable(false);
                }
            }
         });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipe = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cboKategori = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbFacelift = new javax.swing.JRadioButton();
        rbHatchback = new javax.swing.JRadioButton();
        txtMerk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMobil = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 222, 186));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 144, 126));
        jLabel1.setText("PROGRAM MANAJEMEN SHOWROOM ELECTRIC CAR");

        jPanel2.setBackground(new java.awt.Color(171, 196, 170));

        cboKategori.setBackground(new java.awt.Color(243, 222, 186));
        cboKategori.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        cboKategori.setForeground(new java.awt.Color(103, 93, 80));
        cboKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LMPV", "SUV", "MPV", "Sedan", "LCGC" }));

        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(103, 93, 80));
        jLabel2.setText("Merk");

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(103, 93, 80));
        jLabel3.setText("Tipe");

        bgTipe.add(rbFacelift);
        rbFacelift.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        rbFacelift.setForeground(new java.awt.Color(103, 93, 80));
        rbFacelift.setText("Facelift");
        rbFacelift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFaceliftActionPerformed(evt);
            }
        });

        bgTipe.add(rbHatchback);
        rbHatchback.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        rbHatchback.setForeground(new java.awt.Color(103, 93, 80));
        rbHatchback.setText("Hatchback");

        txtMerk.setBackground(new java.awt.Color(243, 222, 186));
        txtMerk.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        txtMerk.setForeground(new java.awt.Color(103, 93, 80));

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(103, 93, 80));
        jLabel4.setText("Kategori");

        txtKode.setBackground(new java.awt.Color(243, 222, 186));
        txtKode.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        txtKode.setForeground(new java.awt.Color(103, 93, 80));

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(103, 93, 80));
        jLabel5.setText("Kode");

        txtWarna.setBackground(new java.awt.Color(243, 222, 186));
        txtWarna.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        txtWarna.setForeground(new java.awt.Color(103, 93, 80));

        jLabel6.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(103, 93, 80));
        jLabel6.setText("Warna");

        txtSearch.setBackground(new java.awt.Color(243, 222, 186));
        txtSearch.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(103, 93, 80));

        tbMobil.setBackground(new java.awt.Color(243, 222, 186));
        tbMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbMobil);

        btnSearch.setBackground(new java.awt.Color(243, 222, 186));
        btnSearch.setForeground(new java.awt.Color(103, 93, 80));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(243, 222, 186));
        btnUpdate.setForeground(new java.awt.Color(103, 93, 80));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(243, 222, 186));
        btnDelete.setForeground(new java.awt.Color(103, 93, 80));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(243, 222, 186));
        btnExit.setForeground(new java.awt.Color(103, 93, 80));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(243, 222, 186));
        btnTambah.setForeground(new java.awt.Color(103, 93, 80));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(243, 222, 186));
        btnClear.setForeground(new java.awt.Color(103, 93, 80));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbFacelift)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTambah)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbHatchback)
                                    .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnClear)
                        .addGap(71, 71, 71)
                        .addComponent(btnUpdate)
                        .addGap(57, 57, 57)
                        .addComponent(btnDelete)
                        .addGap(52, 52, 52)
                        .addComponent(btnExit)
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHatchback)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFacelift, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnExit)
                    .addComponent(btnClear))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFaceliftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFaceliftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFaceliftActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String merk = txtMerk.getText();
        String kode = txtKode.getText();
        String kategori = (String) cboKategori.getSelectedItem();
        String warna = txtWarna.getText();
        String tipe = rbFacelift.isSelected() ? "Hatchback" : "Facelift";

        if (merk.isEmpty() || kode.isEmpty() || kategori.isEmpty() || warna.isEmpty() || bgTipe.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                try (Connection conn = config.getConnection()) {
                    String query = "SELECT * FROM mobil WHERE kode = ?";
                    PreparedStatement stmt = conn.prepareStatement(query);
                    stmt.setString(1, kode);
                    ResultSet rs = stmt.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Kode Mobil telah terdaftar", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    } else {
                        // Insert user information into the database
                        query = "INSERT INTO mobil (kode, merk, kategori, tipe, warna) VALUES (?, ?, ?, ?, ?)";
                        stmt = conn.prepareStatement(query);
                        stmt.setString(1, kode);
                        stmt.setString(2, merk);
                        stmt.setString(3, kategori);
                        stmt.setString(4, tipe);
                        stmt.setString(5, warna);
                        stmt.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        txtMerk.setText("");
                        txtKode.setText("");
                        txtWarna.setText("");
                        cboKategori.setSelectedIndex(-1);
                        bgTipe.clearSelection();
                        tampilData();
                    }
                }
            } 
            catch (SQLException ex) {
                System.out.println("Data Gagal Ditambahkan !");
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        int row = tbMobil.getRowCount();
        for (int i=0; i<row; i++){
        model.removeRow(0);}
        
        try {
            if(txtSearch.getText() != null){
                String query = "SELECT * FROM mobil WHERE kode like '%" + txtSearch.getText() + "%'";
                Connection conn = config.getConnection();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(query);
                while(rs.next()){
                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5)};
                model.addRow(data);                      
                }
            }
            else{
                tampilData();
            }
            
        }
        catch (Exception e) {            
            System.out.println("Data Gagal Terbaca !");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtMerk.setText("");
        txtKode.setText("");
        txtWarna.setText("");
        cboKategori.setSelectedIndex(-1);
        bgTipe.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(tbMobil.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Pilih Data Mobil Dulu !", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {           
            String query = "DELETE FROM mobil WHERE kodemobil = '" +txtKode.getText()+"'";
            
            Connection conn = config.getConnection();
            Statement st = conn.createStatement();
            st.execute(query);
            JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
        } catch (Exception e) {
           System.out.println("Data Gagal Dihapus !");
        }
        txtMerk.setText("");
        txtKode.setText("");
        txtWarna.setText("");
        cboKategori.setSelectedIndex(-1);
        bgTipe.clearSelection();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }
    
    private void tampilData(){
        int row = tbMobil.getRowCount();
        for (int i=0; i<row; i++){
        model.removeRow(0);}

    try {
            String query = "SELECT * FROM mobil";
            Connection conn = config.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5)};
                model.addRow(data);                      
            }
        } catch (Exception e) {            
            System.out.println("Data Gagal Terbaca !");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipe;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFacelift;
    private javax.swing.JRadioButton rbHatchback;
    private javax.swing.JTable tbMobil;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtMerk;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtWarna;
    // End of variables declaration//GEN-END:variables
}
